import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import morgan from 'morgan';
import path from 'path';
import { errorHandler } from './middlewares/errorHandler';
import { apiLimiter } from './middlewares/rateLimiter';
import authRoutes from './modules/auth/auth.routes';
import userRoutes from './modules/users/users.routes';
import projectRoutes from './modules/projects/projects.routes';
import notificationRoutes from './modules/notifications/notifications.routes';
import reportRoutes from './modules/reports/reports.routes';
import billingRoutes from './modules/billing/billing.routes';
import { projectTasksRouter, tasksRouter } from './modules/tasks/tasks.routes';
import { taskCommentsRouter, commentsRouter } from './modules/comments/comments.routes';
import { taskTimeRouter, timeRouter } from './modules/timeTracking/timeTracking.routes';
import { taskFilesRouter, projectFilesRouter, filesRouter } from './modules/files/files.routes';
import { allowedOrigins } from './config/cors';
const app = express();
// Render, Railway and friends terminate TLS in front of us. Without this express-rate-limit sees
// the proxy's IP for every caller and buckets the whole internet together.
if (process.env.NODE_ENV === 'production') app.set('trust proxy', 1);
app.use(helmet({ crossOriginResourcePolicy: { policy: 'cross-origin' } }));
app.use(cors({ origin: allowedOrigins(), credentials: true }));
app.use(express.json({ limit: '10mb' }));
app.use(express.urlencoded({ extended: true }));
if (process.env.NODE_ENV !== 'test') app.use(morgan(process.env.NODE_ENV === 'production' ? 'combined' : 'dev'));
app.use('/uploads', express.static(path.join(process.cwd(), process.env.UPLOADS_DIR || 'uploads')));
app.use('/api', apiLimiter);
app.use('/api/auth', authRoutes);
app.use('/api/users', userRoutes);
app.use('/api/notifications', notificationRoutes);
app.use('/api/billing', billingRoutes);
app.use('/api/projects', projectRoutes);
app.use('/api/projects/:projectId/tasks', projectTasksRouter);
app.use('/api/projects/:projectId/reports', reportRoutes);
app.use('/api/projects/:projectId/files', projectFilesRouter);
app.use('/api/tasks/:taskId/comments', taskCommentsRouter);
app.use('/api/tasks/:taskId/time', taskTimeRouter);
app.use('/api/tasks/:taskId/files', taskFilesRouter);
app.use('/api/tasks', tasksRouter);
app.use('/api/comments', commentsRouter);
app.use('/api/time', timeRouter);
app.use('/api/files', filesRouter);
app.get('/health', (_req, res) => res.json({ status: 'ok', timestamp: new Date().toISOString() }));
app.use((_req, res) => res.status(404).json({ success: false, message: 'Route not found' }));
app.use(errorHandler);
export default app;
